### ISSUE TITLE
Mac version, does not see the additional hard drive

### ISSUE THREAD

**Issue by marchino65** [Photonsters/PhotonFileValidator#10]
If I can, I found a problem on the MAC version, the program only recognizes the main hardisk but not the second one.

Thank you

**Comment by bonosoft** [comment]
Are you talking about the "Open file" dialog in the application?

**Comment by marchino65** [comment]
Hi,
yes, you can see the attached file

Thanks so much
https://www.dropbox.com/s/jlz2jul6qi7jxy8/PhotonFileValidation.jpg?dl=0

**Comment by bonosoft** [comment]
Version 1.3 now uses native open dialogs.

**Comment by marchino65** [comment]
Hi,
Thank you so much, it works perfectly.

Marco A.
