### ISSUE TITLE
Potential to interact with meshmixer via CLI with this library

### ISSUE THREAD

**Issue by X3msnake** [Photonsters/PhotonFileValidator#14]
https://github.com/meshmixer/mm-api

**Comment by mmgarcia30** [comment]
That's really interesting, 

But perhaps it's more interesting for the Chitu Slicer to allow to send command line to slicer from meshmixer to slicer in just one step.

Regards

**Comment by X3msnake** [comment]
@mmgarcia30 

Chitu? Meshmixer to chitu?

What you are saying may make sense in some new project but does not  make any sense here. Besides that would mean you would have to talk to chitu devs not here.
