### ISSUE TITLE
feature request - add layer height in mm

### ISSUE THREAD

**Issue by webbyeasy** [Photonsters/PhotonFileValidator#16]
I would like to see a simple height readout next the the layer number if possible.
This will be a huge help when identifying problem areas when using 3rd party software that can identify layers using height. IE Flashpoint has a layer slider based on height.

**Comment by bonosoft** [comment]
![zheight](https://user-images.githubusercontent.com/5933560/43462928-aaa8c928-94d7-11e8-92ad-08e2fb348ef1.png)

Its always been there...
