### ISSUE TITLE
Volume gave negative result

### ISSUE THREAD

**Issue by ImperfectSense** [Photonsters/PhotonFileValidator#19]
I ended up getting a negative value for the volume of this model.  Not sure why!

![image](https://user-images.githubusercontent.com/44889855/48246318-e5d64780-e3a3-11e8-8a12-face8ac957b2.png)

**Comment by X3msnake** [comment]
@ImperfectSense looks like your model was outside the print area.

i'm going to close this issue since this is a Photon File Editor issue and not a Validator issue

If you still have this issue please open it in the Photon File Editor Project. best wishes
