### ISSUE TITLE
Not Scanning Layers

### ISSUE THREAD

**Issue by uglyduckling81** [Photonsters/PhotonFileValidator#26]
I'm having an issue with Validator not scanning the file at all.
It just says Complete... as soon as it loads the file.
I can scroll through the layers no problem but it's simply not scanning the layers.
I slice in Chitubox to *.photon.
I've tried redownloading the 2.0 version of Validator but it makes no difference.
I'm using Chitubox 1.4.
I thought it might be due to file size but even smaller files give me the same result.
It's not every time but more often than not I can no longer scan with Validator.
Edit: Tried slicing a file in Anycubic Photon Slicer that wasn't working after slicing in Chitubox and it scanned the layers fine.

**Comment by bonosoft** [comment]
Yes, Chitubox 1.4 has some issues generating preview images with some models. Use 1.3 or AnyCubic slicer and it works fine. I am investigating the issue to prevent the issue from stopping the analysis of the file.
