### ISSUE TITLE
Linux version installs but does not run

### ISSUE THREAD

**Issue by NardJ** [Photonsters/PhotonFileValidator#3]
I have installed PFV on Linux  Mint 18.3. When starting photonfileviewer.run nothing happens. (it is marked as executable)

**Comment by bonosoft** [comment]
Ok, I will try to install a Linux desktop someware and test it.

Until then, you can run it from the command line: java -jar PhotonFileCheck.jar

**Comment by X3msnake** [comment]
@NardJ does this till happen with the new releases?

**Comment by NardJ** [comment]
@X3msnake Extract archive and using "java -jar /home/nard/PhotonFileUtils-OpenGL/plugins/PhotonFileValidator/PhotonFileValidator.jar" it works. I think this should be enough for Linux users.
