### ISSUE TITLE
Jpg / PDF (/Gerber) importer... FEATURE REQUEST

### ISSUE THREAD

**Issue by sixtemesseven** [Photonsters/PhotonFileValidator#33]
Besides printing, the photonics printer seem great for exposing PCB for DIY PCB etching :)
They are effectifly a UV display which eliminate the need for transfer foils and projector foils with a uv exposure bed.

Unfortunatly there is no good way of turning the common "gerber" file formats into stl.
However, if I could only insert a single image (from a 1:1 pdf or a 1:1 jpg) exposing would get really easy.

**Comment by X3msnake** [comment]
this is not the pourpose of validator.
from your pcd ide export a png at 538dpi format the image to have 1440x2560 pixels and use photon file editor to create a single bottom exposure for your newly created pcd
