### ISSUE TITLE
AA Settings

### ISSUE THREAD

**Issue by mosaike** [Photonsters/PhotonFileValidator#34]
Hello , First of all Thanks for this great tool.
Its not an Issue, 
but i think we can talk a bit more about it.

My gues is that the 5x AA settings messing up the dimensions more than the 3x settings.
Also the print comes out more sticky,( As the resin  at the edges dont get cured) for full time.

But that can be an advance for hiding the layer lines as the semi-hardend resin sticks to the print and get postcured after wards , and giving a more even surface.

But i think the 5X blur settings are to wide,  messing up the dimensions  and hardening to much?

I want to talk a bit about finding the right settings.

I think one pixel is 0,05mm(0,047+space) .
So when u do 4x AA, and have a layer Height of 0.0125 you end up with kind of even blocks 0.0125 z * 0.0125 xy( 0.05mm pixel/4xAA=0.0125 )  

2XAA for 0.025mm Layer Height.
Giving you an even resolution and even surface in xyz.

I would say go for 16x AA for max quality.
But i think thats to much of nearly cured resin, so  i think dont go higher than 8x times.

Which Anti Alias Method do you prefer ? Gaussian, Blur, Smooth?  2x 4x 8x 16x?   3x 5x? 

It seems like the AA function from Chitubox using the Smooth method.
Also the slices fast played after each other looking like they retain best dimmensions with the Smooth Method.

I like to use formware 3d for slicing than convert to AA. With the PhotonFileValidator.
As Chitubox giving me bad slicing results.(Not accurate somehow downsampled)

Greetings

**Comment by X3msnake** [comment]
The filter application that bundles with the Validator is not a substitute for real AA. it is just Blur
