### ISSUE TITLE
Mouse Pointer Offset

### ISSUE THREAD

**Issue by Zappline** [Photonsters/PhotonFileValidator#67]
Since I updated to the latest version I have a lot of trouble with the pointer when I try to use swap I have to hit the upper left corner of each pixel for it to work. I can no longer just hit the middle of the pixel and it's rather annoying I must say. Hopefully its not to hard to remedy :)

**Comment by DrMcCoy** [comment]
Same. Might be related to #57?

**Comment by X3msnake** [comment]
## PHOTON FILE VIEWER IS NO LONGER MANTAINED OR DEVELOPED!

Use [UVTools](https://github.com/sn4k3/UVtools/blob/master/README.md) by Master Photonster Tiago Conceição instead
