### ISSUE TITLE
[BUG] does not open *.ctb files

### ISSUE THREAD

**Issue by porlock** [Photonsters/PhotonFileValidator#68]
I tried to open file from attachment, no luck, even when i rename it to photon.
[_xenomorph-wall-mount.zip](https://github.com/Photonsters/PhotonFileValidator/files/4460729/_xenomorph-wall-mount.zip)

**Comment by X3msnake** [comment]
CTB is a completely different format

Only format that is just a extension difference is cbddlp and that Photon Validator opens.

Not sure if anyone is working on supporting CTB yet

**Comment by X3msnake** [comment]
https://github.com/ddv2005/resin_xp_finder_mars_pro/
https://github.com/ddv2005/resin_xp_finder_mars_pro/blob/master/template/ctb_hextemplate.bt
