### ISSUE TITLE
Feature request: Flip/mirror individual layer

### ISSUE THREAD

**Issue by matrixes** [Photonsters/PhotonFileValidator#78]
This application is a life (well, model really) saver! Nice job!

I have one gripe with it though, and it's the lack of being able to to flip/mirror layers. I use Chitubox as my slicer and it generally works very well in tandem with Photon file validator.
However, images in Photon file validator are very cumbersome to scan when combined with Chitubox; locating island/pixel issues in Chitubox, as reported by Photon file validator, is easier when orienting the viewport in Chitubox from bottom to top (the model prints "upwards" instead of "downwards" in Chitubox viewport). If instead a model is oriented in Chitubox the same way as Photon file validator displays, the view will be _heavily_ obstructed by the actual supports making it almost impossible to locate and work with the reported island.

If it was possible to visually flip/mirror a layer in Photon file validator, I believe it would make the scanning easier and faster, at least in Chitubox.

This request is only asking for a visual flip/mirror feature (including the X/Y crosshair location of the problem found); I don't want it to _save_ the layer as flipped becuase that would increase the risk of failed prints tenfold.

**Comment by X3msnake** [comment]
## PHOTON FILE VIEWER IS NO LONGER MANTAINED OR DEVELOPED!

Use [UVTools](https://github.com/sn4k3/UVtools/blob/master/README.md) by Master Photonster Tiago Conceição instead
