### ISSUE TITLE
Feature Request: Dynamic resize of the UI for high resolution

### ISSUE THREAD

**Issue by vbproggi** [Photonsters/PhotonFileValidator#80]
It will be fine, it the UI can be adapted like a "Responsive" design. What i mean is the dynamic resizing of controls when using high resolutions (4K). 

regards
vbproggi

**Comment by eried** [comment]
Meanwhile you can manually set the properties of the app in Windows, in compatibility - High DPI settings - Enhanced (System)

**Comment by vbproggi** [comment]
Thanks for your info. I saw it and use it now. Everything fine.

**Comment by eried** [comment]
> Thanks for your info. I saw it and use it now. Everything fine.

By the way, check UVtools

**Comment by vbproggi** [comment]
Used Solution is the manually set of the properties of the app in Windows.
