### ISSUE TITLE
Feature request: Layer change key + enter for accepting changes

### ISSUE THREAD

**Issue by Backmann13** [Photonsters/PhotonFileValidator#86]
Hey,
Love the Validator and using it everytime I print a model. But I think you could implement using wsad (or arrows, or +/-) for changing layers and magnification out of pixel change and enter for accepting pixel change. I think it would greatly improve the workflow.
Thanks and keep up the good work!
Bee

**Comment by X3msnake** [comment]
## PHOTON FILE VIEWER IS NO LONGER MANTAINED OR DEVELOPED!

Use [UVTools](https://github.com/sn4k3/UVtools/blob/master/README.md) by Master Photonster Tiago Conceição instead
