### ISSUE TITLE
cant run new windows version, asking for java runtime install

### ISSUE THREAD

**Issue by webbyeasy** [Photonsters/PhotonFileValidator#9]
Previous version installed and ran just fine, new validator version asking to install java runtime.
how to fix? win8 64bit

**Comment by webbyeasy** [comment]
is it possible to have the installer install the required java components like the previous version? I much prefer this then downloading 68mb worth of java.

**Comment by bonosoft** [comment]
Now installers are in two versions, one for users that have java installed, and one for the others.

**Comment by X3msnake** [comment]
@bonosoft 
awsome decision, since there are lots of users for south africa that don't have the same good net connections as we have :)
